// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA59mnGOxN5vl7akeRch5lfLmZLmUZkMQ',
    appId: '1:325520034717:web:27567e5f8dd1c58b4c7d74',
    messagingSenderId: '325520034717',
    projectId: 'chatapp-77b08',
    authDomain: 'chatapp-77b08.firebaseapp.com',
    storageBucket: 'chatapp-77b08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcM-mLeJpGB1j0PJRI61BAWPXnnou8q2g',
    appId: '1:325520034717:android:3338cad5886501694c7d74',
    messagingSenderId: '325520034717',
    projectId: 'chatapp-77b08',
    storageBucket: 'chatapp-77b08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP6G1nN23YL6XVf_8uYAfyNedo0kp93Rw',
    appId: '1:325520034717:ios:fff42d67fbfe8cc94c7d74',
    messagingSenderId: '325520034717',
    projectId: 'chatapp-77b08',
    storageBucket: 'chatapp-77b08.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP6G1nN23YL6XVf_8uYAfyNedo0kp93Rw',
    appId: '1:325520034717:ios:fff42d67fbfe8cc94c7d74',
    messagingSenderId: '325520034717',
    projectId: 'chatapp-77b08',
    storageBucket: 'chatapp-77b08.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA59mnGOxN5vl7akeRch5lfLmZLmUZkMQ',
    appId: '1:325520034717:web:f5c1bc9723c9c8124c7d74',
    messagingSenderId: '325520034717',
    projectId: 'chatapp-77b08',
    authDomain: 'chatapp-77b08.firebaseapp.com',
    storageBucket: 'chatapp-77b08.firebasestorage.app',
  );

}